# @package _global_

# Path to the train config file that was used for training
train_config: "configs/train/reranker.yaml"

# Basic evaluation settings
train:
  seed: 42
  data_proportion: 1.0  # Use full dataset for evaluation
  size: small           # Match the training dataset size
  dropout: 0.07         # Default dropout value
  output_dir: "./outputs/eval"  # Temporary output dir for evaluation
  hf_args:
    per_device_eval_batch_size: 2
    bf16: true
    fp16: false

# Experiment configuration (should match training)
exp:
  name: "reranker"
  model_name: "answerdotai/ModernBERT-large"
  num_negatives: 9
  max_length: 512