# @package _global_


train:
  seed: 42
  output_dir: "./outputs/debug"
  do_train: true
  do_initial_eval: false
  use_wandb: false
  data_proportion: 0.01
  eval_on_train: true
  max_length: 16384
  train_ds: "GAIR/LIMO-v2"
  sync_empty_cache: true
  enable_profiler: true
  # Profiler configuration
  profiler:
    wait: 0
    warmup: 0
    active: 1
    repeat: 9999
    output_dir: "./log/models/run-32-offload-eval/"
  hf_args:
    per_device_train_batch_size: 1
    per_device_eval_batch_size: 1
    gradient_accumulation_steps: 1
    num_train_epochs: 1
    learning_rate: 5e-6
    warmup_ratio: 0.0
    lr_scheduler_type: "cosine"
    eval_strategy: "epoch"
    save_strategy: "epoch"
    load_best_model_at_end: true
    gradient_checkpointing: true
    gradient_checkpointing_kwargs:
      use_reentrant: true
    bf16: true
    fp16: false
    deepspeed: "./configs/ds_zero3_debug.json"
    logging_strategy: "steps"
    logging_steps: 1
exp:
  name: "reasoning"
  loss_tol: 0.0
  loss_type: "erm"
  model_name: "Qwen/Qwen2.5-32B-Instruct"
  use_lora: true
  lora:
    r: 16
    lora_alpha: 32
    target_modules: ["q_proj", "v_proj", "k_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]
    lora_dropout: 0.1
    bias: "none"
    task_type: "CAUSAL_LM"