# @package _global_

train:
  seed: 42
  output_dir: "./outputs/simple_debug"
  do_train: true
  do_initial_eval: false
  use_wandb: false
  data_proportion: 0.01  # Use only 1% of data for debugging
  max_length: 16384
  enable_profiler: true
  
  # Profiler configuration
  profiler:
    wait: 0
    warmup: 0
    active: 1
    repeat: 9999
    output_dir: "./log/7b-baseline/"
  
  bf16: true
  fp16: false
  deepspeed: "./configs/ds_zero3.json"
  
  hf_args:
    per_device_train_batch_size: 1
    per_device_eval_batch_size: 1
    gradient_accumulation_steps: 1
    num_train_epochs: 1
    learning_rate: 5e-5
    warmup_ratio: 0.03
    lr_scheduler_type: "cosine"
    eval_strategy: "no"
    save_strategy: "no"
    gradient_checkpointing: true

model:
  name: "Qwen/Qwen2.5-7B-Instruct"
  use_flash_attention: true
  use_lora: true
  
  lora:
    r: 8
    lora_alpha: 16
    target_modules: ["q_proj", "v_proj", "k_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]
    lora_dropout: 0.1
    bias: "none"