# @package _global_

hydra:
  mode: MULTIRUN
  # Make the sweeper explicit and sequential
  sweeper:
    # Hydra 1.3+ path:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    # (If you're on Hydra 1.1/1.2 use: hydra._internal.basic_sweeper.BasicSweeper)
    max_batch_size: 1              # submit one job at a time → preserves order
    params:
      exp.model_name: roberta-base
      exp.loss_alpha: 0.03, 0.05, 0.07, 0.005
      exp.loss_type: l2,l1,dual

  # Ensure sequential launching (no parallel launcher)
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher

  # Optional: get deterministic per-job folders 0,1,2,...
  sweep:
    dir: ./multirun
    subdir: ${hydra.job.num}  # 0,1,2,... in the iteration order

train:
  seed: 42
  output_dir: "./outputs/bias/run-${exp.model_name}-${exp.loss_type}-alpha${exp.loss_alpha}"
  do_train: true
  do_initial_eval: true
  use_wandb: true
  wandb_project: "BIAS-v1"
  run_name: "run-${exp.model_name}-${exp.loss_type}-alpha${exp.loss_alpha}"
  data_proportion: 1.0
  eval_on_train: true

  hf_args:
    per_device_train_batch_size: 16
    per_device_eval_batch_size: 16
    gradient_accumulation_steps: 4
    num_train_epochs: 4
    learning_rate: 2e-5
    lr_scheduler_type: "linear"
    warmup_ratio: 0.1
    weight_decay: 0.01
    eval_strategy: "epoch"
    save_strategy: "epoch"
    load_best_model_at_end: true
    metric_for_best_model: "accuracy"
    greater_is_better: true

exp:
  name: "bias"
  loss_alpha: 1.0
  loss_type: "erm"
  model_name: "roberta-base"
