# @package _global_

hydra:
  mode: MULTIRUN
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    params:
      exp.ratio: fair, ones
      exp.model_name: FacebookAI/roberta-large
      exp.loss_type: l2,l1,dual
      exp.tol: 0
      exp.loss_alpha: 10,100,1000,10000

  # Ensure sequential launching (no parallel launcher)
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher

  # Optional: get deterministic per-job folders 0,1,2,...
  sweep:
    dir: ./multirun
    subdir: ${hydra.job.num}  # 0,1,2,... in the iteration order

train:
  seed: 42
  output_dir: "./outputs/bias/run-${exp.model_name}-${exp.loss_type}-alpha${exp.loss_alpha}-${exp.ratio}-${exp.tol}"
  do_train: true
  do_initial_eval: true
  use_wandb: true
  wandb_project: "BIAS-v5"
  run_name: "run-${exp.model_name}-${exp.loss_type}-alpha${exp.loss_alpha}-${exp.ratio}-${exp.tol}"
  data_proportion: 1.0
  eval_on_train: true
  enable_profiler: false
  dropout: 0.0
  profiler:
    wait: 99
    warmup: 0
    active: 1
    repeat: 9999
    output_dir: "./log/bias/${exp.model_name}-${exp.loss_type}-alpha${exp.loss_alpha}-${exp.ratio}-${exp.tol}/"
  hf_args:
    per_device_train_batch_size: 8
    per_device_eval_batch_size: 8
    gradient_accumulation_steps: 1
    num_train_epochs: 5
    learning_rate: 5e-6
    lr_scheduler_type: "linear"
    warmup_ratio: 0.1
    weight_decay: 0.01
    eval_strategy: "epoch"
    save_strategy: "epoch"
    load_best_model_at_end: true
    metric_for_best_model: "accuracy"
    greater_is_better: true
    save_total_limit: 1
exp:
  name: "bias"
  loss_alpha: 10
  loss_type: l2
  model_name: FacebookAI/roberta-large
  ratio: fair # Options: "fair", "ones"
  tol: 0.0
