# @package _global_

hydra:
  mode: MULTIRUN
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    params:
      exp.loss_type: hf,erm,l2,l1
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
  sweep:
    dir: ./multirun
    subdir: ${hydra.job.num}

train:
  seed: 42
  output_dir: "./outputs/reasoning"
  do_train: true
  do_initial_eval: false
  use_wandb: true
  wandb_project: "REASONING-v1"
  run_name: "run-${exp.model_name}-${exp.loss_type}-alpha${exp.loss_tol}"
  data_proportion: 1.0
  eval_on_train: true
  max_length: 16384
  train_ds: "GAIR/LIMO-v2"
  sync_empty_cache: true
  # Profiler configuration
  enable_profiler: true
  profiler:
    wait: 0
    warmup: 0
    active: 1
    repeat: 9999
    output_dir: "./log/reasoning/run-0/"
  hf_args:
    per_device_train_batch_size: 1
    per_device_eval_batch_size: 1
    gradient_accumulation_steps: 64
    num_train_epochs: 1
    learning_rate: 5e-6
    warmup_ratio: 0.0
    lr_scheduler_type: "cosine"
    eval_strategy: "no"
    save_strategy: "no"
    # load_best_model_at_end: true
    gradient_checkpointing: true
    gradient_checkpointing_kwargs:
      use_reentrant: true
    bf16: true
    deepspeed: "./configs/ds_zero3.json"
    logging_strategy: "steps"
    logging_steps: 1

exp:
  name: "reasoning"
  loss_tol: 0.0
  loss_type: "erm"
  model_name: "Qwen/Qwen2.5-32B-Instruct"
  use_lora: true
  lora:
    r: 16
    lora_alpha: 32
    target_modules: ["q_proj", "v_proj", "k_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]
    lora_dropout: 0.1
    bias: "none"
    task_type: "CAUSAL_LM"